#####################################################################
# Dockerfile to build xpaas-bpms-eap-docker container image including:
#   - http daemon
#   - EAP 6.1
# Based on XPaaS JBoss EAP docker image
# Version: 1.0
######################################################################

####### BASE ############
FROM xpaas/xpaas_eap:1.0

####### MAINTAINER ############
MAINTAINER "JBoss XPaaS Team" "xpass-eng@redhat.com"

####### BPMS for EAP 6.1 ############
RUN curl --silent --output /tmp/kie-wb.war https://repository.jboss.org/nexus/service/local/repositories/releases/content/org/kie/kie-wb-distribution-wars/6.1.0.CR1/kie-wb-distribution-wars-6.1.0.CR1-eap-6_1.war

####### SCRIPTS ############
WORKDIR /
RUN mkdir -p /jboss/scripts/bpms
ADD conf/scripts/jboss-appserver/startup/1-configure-bpms.sh /jboss/scripts/jboss-appserver/startup/1-configure-bpms.sh
ADD conf/scripts/jboss-appserver/start-jboss.sh /jboss/scripts/jboss-appserver/start-jboss.sh
ADD conf/scripts/bpms/bpms.cli /jboss/scripts/bpms/bpms.cli
ADD conf/scripts/bpms/change-hibernate-dialect.sh /jboss/scripts/bpms/change-hibernate-dialect.sh
ADD conf/bpms-roles.properties /opt/jboss-appserver/standalone/configuration/bpms-roles.properties
ADD conf/bpms-users.properties /opt/jboss-appserver/standalone/configuration/bpms-users.properties